version: '3.7'

services:
  db:
    image: mysql:8.1
    command: 
      --default-authentication-plugin=mysql_native_password
      --bind-address=0.0.0.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports: 
      - 3306:3306
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

  traefik:
    image: traefik:v2.3
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  api-gateway:
    build: ./api-gateway
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-gateway.rule=Host(`api-gateway.localhost`)
    environment:
      - APP_PORT=80
    volumes:
      - ./api-gateway:/var/www

  board-service:
    build: ./board-service
    labels:
      - traefik.enable=true
      - traefik.http.routers.board-service.rule=Host(`board-service.localhost`)
    environment:
      - APP_PORT=80
    volumes:
      - ./board-service:/var/www
    depends_on:
      - db

  lane-service:
    build: ./lane-service
    labels:
      - traefik.enable=true
      - traefik.http.routers.lane-service.rule=Host(`lane-service.localhost`)
    environment:
      - APP_PORT=80
    volumes:
      - ./lane-service:/var/www
    depends_on:
      - db

  ticket-service:
    build: ./ticket-service
    labels:
      - traefik.enable=true
      - traefik.http.routers.ticket-service.rule=Host(`ticket-service.localhost`)
    environment:
      - APP_PORT=80
    volumes:
      - ./ticket-service:/var/www
    depends_on:
      - db

  user-service:
    build: 
      context: .
      dockerfile: ./user-service/Dockerfile
    labels:
      - traefik.enable=true
      - traefik.http.routers.user-service.rule=Host(`user-service.localhost`)
    environment:
      - APP_PORT=80
    volumes:
      - ./user-service:/var/www
    
    depends_on:
      - db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  db_data:

networks:
  default:
    external:
      name: traefik_default
### Need to enable for service discovery `docker network create traefik_default`
