version: '3.7'

services:
  traefik:
    image: traefik:v2.3
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  api-gateway:
    build: ./api-gateway
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-gateway.rule=Host(`api-gateway.localhost`)
    environment:
      - APP_PORT=80
    volumes:
      - ./api-gateway:/var/www

  board-service:
    build: ./board-service
    labels:
      - traefik.enable=true
      - traefik.http.routers.board-service.rule=Host(`board-service.localhost`)
    environment:
      - APP_PORT=80
    volumes:
      - ./board-service:/var/www

  lane-service:
    build: ./lane-service
    labels:
      - traefik.enable=true
      - traefik.http.routers.lane-service.rule=Host(`lane-service.localhost`)
    environment:
      - APP_PORT=80
    volumes:
      - ./lane-service:/var/www

  ticket-service:
    build: ./ticket-service
    labels:
      - traefik.enable=true
      - traefik.http.routers.ticket-service.rule=Host(`ticket-service.localhost`)
    environment:
      - APP_PORT=80
    volumes:
      - ./ticket-service:/var/www

  user-service:
    build: ./user-service
    labels:
      - traefik.enable=true
      - traefik.http.routers.user-service.rule=Host(`user-service.localhost`)
    environment:
      - APP_PORT=80
    volumes:
      - ./user-service:/var/www

networks:
  default:
    external:
      name: traefik_default
### Need to enable for service discovery `docker network create traefik_default`
